### ISSUE TITLE
Undefined variable "c" in spec.py

### ISSUE THREAD

**Issue by bhorowitz** [dhanson/quicklens#4]
I get a global name error when trying to use the rcfft2cl function in spec.py. In particular the variable "c" that is used in lines 586/587 do not appear to be defined anywhere? What is this variable supposed to represent and how should it be defined?

**Comment by dhanson** [comment]
Looks like a typo, and it should be 'cvec'.

**Comment by dhanson** [comment]
Fixed by f72dab84a8c2
